[package]
name = "bevy-ball-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.15"
bevy_embedded_assets = "0.12.0"
rand = "0.9"

wgpu-hal = {version="27.0.2",features = ["vulkan"]}
